import './_strict.mjs';
const { habitSummary, habitHeadline } = await import('../src/utils/habitInsights.js');
const T = (type, pnlNum, needsLabel = false) => ({ type, pnlNum, needsLabel });
const s = habitSummary([T('win', 100), T('toxic_win', 310), T('toxic_win', 12), T('double_failure', -820), T('good_loss', -50), T(undefined, 40, true), T('missed_trade', 0)]);
console.assert(s.labeled === 5 && s.needsLabel === 1, 'labelled vs unlabelled counted (missed ignored)');
console.assert(s.toxicWins.count === 2 && s.toxicWins.pnl === 322, 'toxic wins');
console.assert(s.doubleFailures.pnl === -820 && s.ruleBreaks.count === 3, 'double failures + rule breaks');
const h = habitHeadline(s);
console.assert(h.tone === 'warn' && h.text === "Toxic wins: 2 trades, +$322 you can't count on · Double failures cost you −$820", h.text);
console.assert(habitHeadline(habitSummary([T('win', 10)])).text === 'Clean so far: all 1 trade followed your plan.', 'clean');
console.assert(habitHeadline(habitSummary([T(undefined, 10, true)])) === null, 'nothing labelled -> no headline');
console.log('✓ habit insights');
const { validLabelIds } = await import('../src/utils/habitInsights.js');
console.assert(validLabelIds(57.84).join() === 'win,toxic_win', 'win options');
console.assert(validLabelIds(-20.72).join() === 'good_loss,double_failure', 'loss options: no Toxic Win on a loss');
console.assert(validLabelIds(2).join() === 'breakeven,toxic_be', 'breakeven band');
console.log('✓ label options follow the outcome');
const odd = habitSummary([{ type: 'toxic_win', pnlNum: -20.72, needsLabel: false }]);
console.assert(odd.toxicWins.count === 0 && odd.doubleFailures.count === 1, 'rule break on a loss counts as double failure');
console.log('✓ inconsistent legacy labels classified by result');
